---
title: "Natanael Soares Leite's CV"
author: Natanael Soares Leite
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1LtfUnLPXcRZuNjlGvGKXYg3YjWuSh41NnWO-9pZmy_I",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Veja este CV online com o link _https://natanaelsl.netlify.app/media/_")
} else {
  cat("[<i class='fas fa-download'></i> Download o PDF deste CV](https://github.com/Natanaelsl/cv/raw/master/natanael_cv.pdf)")
}
```

Contatos {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Construído com o R *package* [**pagedown**](https://github.com/rstudio/pagedown). 

O código está disponível em [github.com/nstrayer/cv](https://github.com/Natanaelsl/cv).

Última atualização em `r Sys.Date()`.



Main
================================================================================

Natanael Soares Leite {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Educação {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('educação')
```


Experiência Profissional {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('experiência')
```



```{r}
CV %<>% print_links()
```

